name: Build and Publish
on:
  push:
    branches: [main]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '***NO_CI***')"
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "53619745+rnbot@users.noreply.github.com"
          git config --global user.name "React Native Bot"

      - name: Set up Node 20
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: main
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - name: Install package dependencies
        run: yarn install

      - name: Perform validation
        run: yarn ci

      - name: Publish
        run: npx --no-install beachball publish --yes --branch main --token ${{ secrets.NPM_TOKEN }}
