name: Pull Request
on: pull_request
jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        node-version: [14, 16, 17]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          fetch-depth: 0

      - name: Install package dependencies
        run: yarn install

      - name: Check for change files
        run: npx --no-install beachball check --branch main

      - name: Perform Validation
        run: yarn ci
